#!/bin/bash
#
#	Use SSH to log into the Mysql Docker container.
#
bin=`dirname $0`
#. $bin/../env.sh
. $bin/env.sh

OPTION="-o StrictHostKeyChecking=no"
echo ssh ${OPTION} root@${DOCKER_IP} -p ${SSH_PORT} "$@"
     ssh ${OPTION} root@${DOCKER_IP} -p ${SSH_PORT} "$@"
